export const DEMO_WORKFLOW_DEFINITION = {
    nodes: [
        {
            id: 'demo-query',
            type: 'GenNode',
            dragHandle: '.drag-handle',
            data: { type: 'QUERY', inputs: {}, outputs: [] },
            position: { x: 100, y: 80 },
            deletable: false,
        },
        {
            id: 'demo-retriever',
            type: 'GenNode',
            dragHandle: '.drag-handle',
            data: { type: 'RETRIEVER', inputs: {}, outputs: [] },
            position: { x: 100, y: 220 },
            deletable: false,
        },
        {
            id: 'demo-response',
            type: 'GenNode',
            dragHandle: '.drag-handle',
            data: { type: 'RESPONSE', inputs: {}, outputs: [] },
            position: { x: 100, y: 360 },
            deletable: false,
        },
        {
            id: 'demo-response-model',
            type: 'GenNode',
            dragHandle: '.drag-handle',
            data: {
                type: 'MODEL',
                inputs: {},
                outputs: [],
                isPlaceholder: false,
                firstTime: false,
                isEditing: false,
                configItems: [],
                settingLabel: 'Large Language Model',
                inputType: 'SELECT',
                parentNodeId: 'demo-response',
                modelName: 'google/gemini-2.5-flash',
                stringValue: 'google/gemini-2.5-flash',
            },
            position: { x: 380, y: 295 },
            deletable: true,
        },
        {
            id: 'demo-response-instruction',
            type: 'GenNode',
            dragHandle: '.drag-handle',
            data: {
                type: 'INSTRUCTION',
                inputs: {},
                outputs: [],
                isPlaceholder: true,
                configItems: [],
                settingLabel: 'system_prompt',
                inputType: 'STRING',
                parentNodeId: 'demo-response',
            },
            position: { x: 380, y: 425 },
            deletable: true,
        },
    ],
    edges: [
        {
            id: 'demo-query-to-demo-retriever',
            source: 'demo-query',
            target: 'demo-retriever',
            sourceHandle: 'main-source',
            targetHandle: 'main-target',
            animated: true,
            type: 'default',
        },
        {
            id: 'demo-retriever-to-demo-response',
            source: 'demo-retriever',
            target: 'demo-response',
            sourceHandle: 'main-source',
            targetHandle: 'main-target',
            animated: true,
            type: 'default',
        },
        {
            id: 'demo-response-setting-llm',
            source: 'demo-response',
            target: 'demo-response-model',
            sourceHandle: 'setting-source-Large Language Model',
            targetHandle: 'setting-target',
            type: 'settings',
            animated: false,
            data: { label: 'Large Language Model' },
        },
        {
            id: 'demo-response-setting-instruction',
            source: 'demo-response',
            target: 'demo-response-instruction',
            sourceHandle: 'setting-source-system_prompt',
            targetHandle: 'setting-target',
            type: 'settings',
            animated: false,
            data: { label: 'system_prompt' },
        },
    ],
    blocks: [
        { name: 'query', type: 'query' },
        { name: 'retrieve', type: 'retrieve', collection_name: 'genrag_knowledge_base', top_k: 5 },
        { name: 'answer', type: 'answer', model: 'google/gemini-2.5-flash' },
    ],
};
