export enum AgentEventType {
    CREATED = 'AGENT_CREATED',
    UPDATED = 'AGENT_UPDATED',
    DELETED = 'AGENT_DELETED',
    AGENT_QUERY_COMPLETED = 'AGENT_QUERY_COMPLETED',
    AGENT_DEPLOYED = 'AGENT_DEPLOYED',
    STATUS_CHANGED = 'AGENT_STATUS_CHANGED',
}
